services:
  app:
    build: .
    container_name: app
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017/
    restart: unless-stopped

  mongo:
    image: mongo:7
    container_name: mongo
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  mongo_data: